---

- name: Update homebrew
  homebrew: name=git state=latest update_homebrew=yes

- name: Add extreanal homebrew repos 
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_tap_repos

- name: Install homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: homebrew_packages

- name: Install homebrew cask packages
  homebrew_cask: name={{ item }} state=installed
  with_items: homebrew_cask_packages
